# Generated by Django 5.2.1 on 2025-07-11 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagory',
            options={'verbose_name': 'catagory', 'verbose_name_plural': 'catagories'},
        ),
        migrations.AlterField(
            model_name='catagory',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='vendor.vendor'),
        ),
    ]
